# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a23b4099bf90e56446a928390d10748474011f1b438dbc74ad57eda563b28378237adf48fe95f16e01607d479167f2b0509424da000ea044becd4d42cba236e

test:
  secret_key_base: 90b02abfecba5b1bf1a26d38b1169e0faa9972cb57b2e699fd5c77766154fe21313da4ac5f976835fe545cf93696b98413cec89f9315c98d6f4fe725bf86e318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
